// packages/web/examples/fingerprint-vue/src/App.vue
<template>
  <header>
    <h1>Fingerprint example</h1>
  </header>
  <section>
    <h2>Device fingerprint</h2>
    <p>{{device}}</p>
  </section>
</template>

<script>
export default {
  name: 'App',
  data() {
    return {
      device: null
    };
  },
  components: {
  },
  methods: {},
  mounted() {
    const _self = this;
    const script = document.createElement('script');
    script.src = 'http://localhost:3100/js/analytics.js';
    script.async = true;
    script.onload = function() {
      window.bayonet.analyze({
        jsKey: '123456789',
        onAnalyzedCallback: function (token) {
          _self.device = token.token;
        },
      });
    };

    document.body.appendChild(script);
  },
};
</script>

<style>
#app {}
</style>

// packages/web/examples/fingerprint-angular/src/app/app.component.ts
import { Component, OnInit } from '@angular/core';

@Component({
  selector: 'app-root',
  templateUrl: './app.component.html',
  styleUrls: ['./app.component.scss']
})
export class AppComponent implements OnInit {
  title = 'fingerprint-angular';
  device: string | null = null;

  ngOnInit(): void {
    const _self = this;
    const script = document.createElement('script');
    script.src = 'http://localhost:3100/js/analytics.js';
    script.async = true;
    script.onload = function () {
      window.bayonet.analyze({
        jsKey: '123456789',
        onAnalyzedCallback: function (token: any) {;
          _self.device = token.token;
        },
      });
    };

    document.body.appendChild(script);
  }
}

<style>
</style>

<header role="banner">
  <h1>Fingerprint example</h1>
</header>

<section class="content" role="main">
  <h2>Device</h2>
  <p>{{device}}</p>
</section>
