// packages/web/examples/fingerprint-react-npm/src/App.js
import { useState, useEffect } from 'react';

import fingerprint from '@bayonetio/fingerprint';

function App() {
  const [device, setDevice] = useState(null);

  useEffect(() => {
    fingerprint.analyze({
      jsKey: '123456789',
      onAnalyzedCallback: function (token) {
        setDevice(() => token.token);
      },
    });
  }, []);

  return (
    <div className="App">
      <header className="App-header">
        Fingerprint example
      </header>
      <section>
        <div>device</div>
        <div>{device}</div>
      </section>
    </div>
  );
}

export default App;

// packages/web/examples/fingerprint-vue-npm/src/App.vue
<template>
  <header>
    <h1>Fingerprint example</h1>
  </header>
  <section>
    <h2>Device fingerprint</h2>
    <p>{{device}}</p>
  </section>
</template>

<script>
import fingerprint from '@bayonetio/fingerprint';

export default {
  name: 'App',
  data() {
    return {
      device: null
    };
  },
  mounted() {
    const _self = this;
    fingerprint.analyze({
      jsKey: '123456789',
      onAnalyzedCallback: function (token) {
        _self.device = token.token;
      },
    });
  },
};
</script>

<style>
#app {
}
</style>
