// packages/web/examples/fingerprint-angular-npm/src/app/app.component.ts
import { Component,  OnInit } from '@angular/core';

import bayonet from '@bayonetio/fingerprint';

@Component({
  selector: 'app-root',
  templateUrl: './app.component.html',
  styleUrls: ['./app.component.scss']
})
export class AppComponent implements OnInit {
  title = 'fingerprint-angular-npm';
  device: string | null = null;

  ngOnInit(): void {
    const _self = this;
    bayonet.analyze({
      jsKey: '123456789',
      onAnalyzedCallback: function (token: any) {;
        _self.device = token.token;
      },
    });
  }
}

<style>
</style>

<header role="banner">
  <h1>Fingerprint example</h1>
</header>

<section class="content" role="main">
  <h2>Device</h2>
  <p>{{device}}</p>
</section>

// packages/web/examples/fingerprint-vue-npm/src/App.vue
<template>
  <header>
    <h1>Fingerprint example</h1>
  </header>
  <section>
    <h2>Device fingerprint</h2>
    <p>{{device}}</p>
  </section>
</template>

<script>
import fingerprint from '@bayonetio/fingerprint';

export default {
  name: 'App',
  data() {
    return {
      device: null
    };
  },
  mounted() {
    const _self = this;
    fingerprint.analyze({
      jsKey: '123456789',
      onAnalyzedCallback: function (token) {
        _self.device = token.token;
      },
    });
  },
};
</script>

<style>
#app {
}
</style>
